config/routes.rb
Rails.application.routes.draw do

  resources :students do
    collection { post :upload }
    collection { get :import }
  end

  root "session#new"

  resources :users, :except => [:delete]

  resources :session, only: [:new, :create]
    delete 'logout' => 'session#destroy'

  resources :students, only: [:index, :import, :show]

  resources :students do
    resources :teams, only: [:update]
  end

  resource :master_pass, only: [:edit, :update]

end

app/models/student.rb
class Student < ActiveRecord::Base
  # validates :team_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :grade, presence: true
  validates :gpa, presence: true
  validates :number_of_detentions, presence: true
  validates :shirt_size, presence: true
  validates :food_allergies, presence: true

  belongs_to :team
  has_one :teacher, through: :team

  require 'csv'

  def is_assigned?
    self.team_id != 0
  end

  def full_name=(name)
    self.first_name = name.split(' ')[0]
    self.last_name = name.split(' ')[1]
    return name
  end

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end

  def self.upload(file)
    puts "================================"
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      attributes = row.to_hash
      attributes[:food_allergies] =attributes.delete :allergies
      attributes[:grade] =attributes.delete :grade_level
      attributes[:number_of_detentions] =attributes.delete :detentions
      Student.create!(attributes)
    end
  end
end

app/controllers/students_controller.rb
# student1 = Student.create(first_name: 'lissie', last_name: 'huang', gender: 'female', image_path: 'x', grade: 'freshman', gpa: 123, number_of_detentions: 5, shirt_size: 's', food_allergies: 'none')
# student2 = Student.create(first_name: 'lissie', last_name: 'huang', gender: 'female', image_path: 'x', grade: 'freshman', gpa: 123, number_of_detentions: 5, shirt_size: 's', food_allergies: 'none')
# students = [student1, student2]

# render

class StudentsController < ApplicationController
require 'bigdecimal'

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def import
    # Student.import(params[:file])
    # redirect_to '/students'
  end

  def upload
    Student.upload(params[:file])
    redirect_to '/'
  end
end

app/views/students/_eligible_students.html.erb
<section class='eligible-students'>

  <% if current_user.team.allow_update(student)[0] == true %>
    <h2 id='student-name'><%= link_to "#{student.first_name} #{student.last_name}", student_path(student) %></h2>

    <table class="table-center">
      <tr>
        <td class="team-name">
          <% if student.team %>
            <span class='team-name'>Team <%=student.team.name.capitalize %></span>
          <% else %>
            <span class='team-name'>Team UNASSIGNED</span>
          <% end %>
        </td>
        <td class="student-info"><%=student.gpa.round(1) %>/4.0</td>
        <td class="student-info"><%=student.grade %></td>
        <td class="student-info"><%=student.gender %></td>
        <td class="student-info"><%=student.number_of_detentions %></td>
      </tr>
    </table>
    <table class="table-center">
      <tr>
        <td>
          <% if current_user.has_student?(student) %>
          <!-- nothing  -->
          <% elsif current_user.team.allow_update(student)[0] == true %>
            <span><%= link_to "Add to my Team", "teams/#{current_user.team.id}/students/#{student.id}", class: 'add-student-button btn btn-success' %></span>
            <!-- You're not the admin && you don't already have this student on your team 
            && adding this student to your team WOULD break the diversity rules -->
          <% else current_user.team.allow_update(student)[0] == false %>
            <span class='btn btn-success unaddable'>?</span>
          <% end %>
        </td>
      </table>
      <table class="ineligibility">
        <td>
          <% if current_user.team.allow_update(student)[0] == false %>
            <ul>
            <% current_user.team.allow_update(student)[1].each do |problem| %>
              <li><%= problem %></li>
            <% end %>
            </ul>
          <% end %>
        </td>
      </tr>
    </table>
  <% end %>
</section>

app/views/students/_student_list.html.erb
<div class="container">

  <button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-info-sign"></button>

  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Rules for adding students</h4>
        </div>
        <div class="modal-body">
          <ul>
            <li>Your team must have gender diversity. </li>
            <li>Your team may not have an average gpa of 2.0 or lower</li>
            <li>Your team may not have an average gpa of 3.6 or higher</li>
            <li>10-15 students per team is preferred</li>
        </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

<section class='student-master-list'>
  <% students.each do |student| %>
    <%= render partial: 'summary', locals: {student: student} %>
  <% end %>
</section>

app/views/students/_summary.html.erb
<section class='student-summary'>
  <h2 id='student-name'><%= link_to "#{student.first_name} #{student.last_name}", student_path(student) %></h2>

  <table class="table-center">
    <tr>
      <td class="team-name">
        <% if student.team %>
          <span class='team-name'>Team <%=student.team.name.capitalize %></span>
        <% else %>
          <span class='team-name'>Currently Unassigned</span>
        <% end %>
      </td>
      <td class="student-info"><%=student.gpa.round(1) %>/4.0</td>
      <td class="student-info"><%=student.grade %></td>
      <td class="student-info"><%=student.gender %></td>
      <td class="student-info"><%=student.number_of_detentions %></td>
    </tr>
  </table>
  <table class="table-center">
    <tr>
      <td>
        <% if current_user.is_admin? %>
          <% if student.is_assigned? %>
            <span><%= link_to "Remove Student Assignment", "students/#{student.id}/teams/11", class: 'add-student-button btn btn-success' %></span>
          <% end %>
          <!-- You're not the admin && you don't already have this student on your team
          && adding this student to your team wouldn't break the diversity rules -->
        <% elsif current_user.has_student?(student) %>
        <!-- nothing  -->
        <% elsif current_user.team.allow_update(student)[0] == true %>
          <span><%= link_to "Add to my Team", "/students/#{student.id}/teams/#{current_user.team.id}", class: 'add-student-button btn btn-success' %></span>
          <!-- You're not the admin && you don't already have this student on your team
          && adding this student to your team WOULD break the diversity rules -->
        <% else current_user.team.allow_update(student)[0] == false %>
          <span class='btn btn-success unaddable'>?</span>
        <% end %>
      </td>
    </table>
    <table class="ineligibility">
      <td>
        <% if current_user.team.allow_update(student)[0] == false %>
          <ul>
          <% current_user.team.allow_update(student)[1].each do |problem| %>
            <li><%= problem %></li>
          <% end %>
          </ul>
        <% end %>
      </td>
    </tr>
  </table>
</section>

app/views/students/import.html.erb
<h2>Import Students</h2>

<%= form_tag upload_students_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/students/index.html.erb
<h1>Students List</h1>

<section class='student-master-list'>
  <%= render partial: 'student_list', locals: {students: @students} %>
</section>

app/views/students/show.html.erb
<div id='student-show-page'>
  <h1><%= @student.first_name %> <%= @student.last_name %></h1>
  <div class="profile-pic">
    <%= image_tag "default.png" %>
  </div>
  <ul class=''>
    <li>Currently on Team <%= @student.team.name.capitalize%></li>
    <li>Assigned Teacher: <%= @student.teacher.first_name %> <%= @student.teacher.last_name %></li>
    <li>Gender: <%= @student.gender %></li>
    <li>Grade: <%= @student.grade %></li>
    <li>GPA: <%= @student.gpa.round(2) %>/4.0</li>
    <li>Detentions Served: <%= @student.number_of_detentions %></li>
    <li>Shirt Size: <%= @student.shirt_size.capitalize %></li>
    <li>Food Allergies: <%= @student.food_allergies %></li>
  </ul>

  <%= link_to 'Back to Students', students_path, class: 'btn btn-success' %>
</div>