config/routes.rb
Rails.application.routes.draw do

  resources :students do
    collection { post :upload }
    collection { get :import }
  end

  root "session#new"

  resources :users, :except => [:delete]

  resources :session, only: [:new, :create]
    delete 'logout' => 'session#destroy'

  resources :students, only: [:index, :import, :show]

  resources :students do
    resources :teams, only: [:update]
  end

  resource :master_pass, only: [:edit, :update]

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  skip_before_action :authorize, only: [:create, :new]

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      puts "logging in"
      log_in @user
      redirect_to students_path
    else
      @errors = ["Invalid Credentials"]
      render partial: 'login', locals: {errors: @errors}
    end
  end

  def new
    @user = User.new
    if request.xhr?
      render partial: 'login'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    if logged_in?
      @current_user = User.find(session[:user_id])
    end
  end

  def logged_in?
    session[:user_id]
  end

end

app/views/session/_login.html.erb
<section id='login-form'>
  <% if @errors %>
    <% @errors.each do |error| %>
      <p> <%= error %></p>
    <% end %>
  <% end %>

  <%= form_for :session, url: session_index_path do |f| %>
    <div class="form-group">
      <%= f.label :email %><br>
      <%= f.email_field :email, placeholder: "email@wbhs.edu" %>
    </div>

    <div class="form-group">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>

    <p>
      <%= f.submit "Log In", class: "btn btn-default" %>
    </p>
  <% end %>
</session>

app/views/session/new.html.erb
<section id='welcome-container'>
  <h1>Welcome to Wild Boar High School</h1>
  <section id='welcome-buttons'>
    <%= link_to 'Login', "session/new", class: 'welcome-button btn btn-info btn-lg btn-block', id: 'login-button' %>
    <%= link_to 'Register', "users/new", class: 'welcome-button btn btn-info btn-lg btn-block', id: 'register-button' %>
  </section>
</section>