config/routes.rb
Rails.application.routes.draw do

  resources :students do
    collection { post :upload }
    collection { get :import }
  end

  root "session#new"

  resources :users, :except => [:delete]

  resources :session, only: [:new, :create]
    delete 'logout' => 'session#destroy'

  resources :students, only: [:index, :import, :show]

  resources :students do
    resources :teams, only: [:update]
  end

  resource :master_pass, only: [:edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true

  has_one :team, foreign_key: :teacher_id
  has_many :students, through: :team

  def has_student?(student)
    self.students.include?(student)
  end

  def is_admin?
    self.role == "admin"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorize, only: [:create, :new]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    @all_students = Student.all
    @current_user = User.find(session[:user_id])
    @students = @user.students
    if @user.role == "admin" && @current_user.role == "teacher"
      redirect_to @current_user
    end
  end

  def new
    @user = User.new

    if request.xhr?
      @errors = []
      render partial: 'new_user', locals: {errors: @errors}
    end
  end

  def create
    new_params = params[:user].except(:master_password)
    @master_pass = MasterPass.first
    if @master_pass.authenticate(params[:user][:master_password])
      @user = User.new(user_params)
      @user.image_path = Faker::Avatar.image
      if @user.save
        new_team = @user.build_team(name: Faker::Commerce.color)
        new_team.save
        session[:user_id] = @user.id
        redirect_to @user
      elsif request.xhr?
        @errors = @user.errors.full_messages
        status 422
        render partial: 'new_user', locals: {errors: @errors}
      else
        @errors = @user.errors.full_messages
        render :new
      end
    elsif request.xhr?
      status 422
      @errors = ["Could not verify master password. Please contact your administrator."]
      render partial: 'new_user', locals: {errors: @errors}
    else
      @errors = ["Could not verify master password. Please contact your administrator."]
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    puts "yoo"
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Your profile was successfully updated.'
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :image_path, :email)
    end
end

app/views/users/_admin.html.erb
<%= image_tag "boss_boar.png" %>

<%= link_to 'Edit the Master Password', edit_master_pass_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br>
    <%= f.text_field :image_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_new.html.erb
<section id="registration-form">
<%= form_for :user, url: users_path do |f| %>
  <% if @errors %>
    <div id="error_explanation">
      <% @errors.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :master_password %><br>
    <%= f.password_field :master_password %>
  </div>
  <div class="actions">
    <%= f.submit "Create New Teacher", class: "btn btn-default" %>
  </div>
<% end %>
</section>

app/views/users/_new_user.html.erb
<section id="registration-form">

 <%= form_for :user, url: users_path, class: 'reg-form' do |f| %>
   <% if errors %>
     <div id="error_explanation">
       <% errors.each do |message| %>
         <p><%= message %></p>
       <% end %>
     </div>
   <% end %>

   <div class="form-group">
     <%= f.label :first_name %><br>
     <%= f.text_field :first_name %>
   </div>
   <div class="form-group">
     <%= f.label :last_name %><br>
     <%= f.text_field :last_name %>
   </div>
   <div class="form-group">
     <%= f.label :email %><br>
     <%= f.email_field :email %>
   </div>
   <div class="form-group">
     <%= f.label :password %><br>
     <%= f.password_field :password %>
   </div>
   <div class="form-group">
     <%= f.label :master_password %><br>
     <%= f.password_field :master_password %>
   </div>
   <div class="actions">
     <%= f.submit "Create New Teacher", class: "register btn btn-default" %>
   </div>
 <% end %>
 </section>

app/views/users/_stats.html.erb
  <p>
  <% if @user.team.students.count > 0 %>
    <span>Email: <%= @user.email %></span><br>
    <span>Average GPA: <%= @user.team.average_gpa %></span><br>
    <span>Total Number of Detentions: <%= @user.team.number_of_detentions %></span><br>
    <span>Average Number of Detentions: <%= @user.team.average_detentions %></span>
  <% else %>
    <span>No statistics available - create a team first!</span>
  <% end %>
  </p>

  <h1><%= @user.first_name %>'s Students</h1>

  <section class='student-master-list'>
    <% @students.each do |student| %>
      <%= render partial: 'students/summary', locals: {student: student} %>
    <% end %>
  </section>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Teachers</h1>

<section id='user-master-list'>
  <section class='user-list'>
    <% @users.each do |user| %>
      <% unless user.role == "admin" %>
        <section class='user-summary'>
          <h2><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></h2>
          <p>
            <span><%= user.email %></span>
          </p>
        </section>
      <% end %>
    <% end %>
  </section>
</section>

app/views/users/new.html.erb
<section id="registration-form">
<%= form_for :user, url: users_path, name: "reg-form" do |f| %>
  <% if @errors %>
    <div id="error_explanation">
      <% @errors.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :master_password %><br>
    <%= f.password_field :master_password %>
  </div>
  <div class="actions">
    <%= f.submit "Create New Teacher", class: "btn btn-default" %>
  </div>
<% end %>
</section>

app/views/users/show.html.erb
<div id='teacher-show-page'>

  <% if current_user.id == @user.id && !current_user.is_admin? %>
    <p><%= link_to "Edit Profile", edit_user_path, class: 'edit-teacher-profile btn btn-success' %></p>
  <%end%>

  <h1><%= @user.first_name %> <%= @user.last_name %></h1>

  <% if @user.is_admin? %>
  <%= render partial: '/users/admin', locals: {user: @user} %>
  <% else %>
    <img src="<%= @user.image_path %>" alt="Profile Pic" />
    <%= render partial: '/users/stats', locals: {user: @user} %>
  <% end %>

</div>