config/routes.rb
Rails.application.routes.draw do

  resources :students do
    collection { post :upload }
    collection { get :import }
  end

  root "session#new"

  resources :users, :except => [:delete]

  resources :session, only: [:new, :create]
    delete 'logout' => 'session#destroy'

  resources :students, only: [:index, :import, :show]

  resources :students do
    resources :teams, only: [:update]
  end

  resource :master_pass, only: [:edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildBoarTeams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="main-container" class="container">
  <header>
    <%= image_tag "boar.png", class: 'mascot' %>
    <div id='titles'>
      <h1><%= link_to 'Wild Boar High School', students_path %></h1>
      <h2><%= link_to 'Farrow Mia', students_path %></h2>
    </div>
    <nav>
    <% if logged_in? %>
      <%= link_to "#{current_user.first_name} #{current_user.last_name}", current_user, class: 'nav-button' %>
      <%= link_to "Student Directory", students_path, class: 'nav-button' %>
      <%= link_to "Teacher Directory", users_path, class: 'nav-button' %>
      <%= link_to 'Log Out', logout_path, method: :delete, class: 'nav-button' %>
    <% else %>
      <%= link_to "Register New Teacher", new_user_path, class: 'nav-button' %>
    <%end %>
    </nav>
  </header>
  <%= yield %>
</div>
</body>
</html>